name: Integration
run-name: Example app integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js and npm
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Test the app
        run: npm run test:prod
      - name: Build the app
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-artifact
          path: dist
  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: app-artifact
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          output_location: app-artifact
