name: Integration
run-name: Example app integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js and npm
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Test the app
        run: npm run test:prod
      - name: Build the app
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-artifact
          path: dist
  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: app-artifact
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pw-mwo-lab'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
